### PR TITLE
sort the Algorithms

### PR DESCRIPTION
**Pull request by SARANYA233**
sorted out the Machine Learning Algorithms in Alphabetical order
issue #377

### CODE REVIEW

**Review by Vishwajeet-11 — APPROVED** [review]

**Comment by Vishwajeet-11** [comment]
hi @SARANYA233, I have reviewed your PR and approved it. Could you please do the same for me in order to merge my PR. For now it's showing 'merging is blocked'. here's my pr #378

**Comment by SARANYA233** [comment]
@Vishwajeet-11 still merging is blocked

**Review by kalyanpavan18 — COMMENTED** [review]
reviewed

**Review by kalyanpavan18 — APPROVED** [review]
Approved

**Comment by SARANYA233** [comment]
@vicky002 Verify and approve this pull request

**Review by Byte7 — APPROVED** [review]

**Pull request merged**
