### PR TITLE
add machine learning books

### PR DESCRIPTION
**Pull request by gayathChandira**

### CODE REVIEW

**Review by Byte7 — CHANGES_REQUESTED** [review]
Hi @gayathChandira , all the links that you have provided are paid ones. The OS books are paid books and not freely available. Inclusion of links providing the pdfs of these would lead to problem later on. Please look at the contribution guidelines, we are collecting only non-paid links.

**Comment by gayathChandira** [comment]
@Byte7 Those pdfs can freely download by given links. You can check it when you click the links, books are downloading automatically.

**Comment by Byte7** [comment]
I checked but these books are listed on Springer as paid books. If you can confirm they are unpaid via a screenshot, I'll merge the PR.

**Comment by codingonHP** [comment]
@gayathChandira Please have a look when you get time and update us so that we can close this.
Thanks for your contribution :)

**Pull request closed without merging**
