### PR TITLE
added some video tutorial links in cryptography.

### PR DESCRIPTION
**Pull request by Santan47**

### CODE REVIEW

**Comment by vicky002** [comment]
Hi @Santan47 , please squash all the commits into one.

**Comment by Santan47** [comment]
Hi, @vicky002, can you please tell me how can I squash all these commits into one.

**Comment by vicky002** [comment]
You can easily find that by googling a bit : https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one

**Comment by Santan47** [comment]
Thanks, @vicky002, that link was really helpful.

**Comment by vicky002** [comment]
Hey @Santan47 , it looks like you haven't squashed all the commits.

**Comment by Santan47** [comment]
Hey @vicky002, sorry for late replying, actually somehow my algowiki branch is deleted in squashing all the commits into one.
And I am trying to recover it, I searched on google about the recovery of the deleted branch but nothing is happening and I cannot be able to reach my rebase file for squashing commits because of my algowiki branch is deleted. Can you please tell me what can I do?

**Pull request closed without merging**
