### PR TITLE
Web2py framework resources

### PR DESCRIPTION
**Pull request by ArushiSinghal**

### CODE REVIEW

**Comment by vicky002** [comment]
I think this is related to Python so it should go under Python Resources, not required to create a separate section for it. What do you think @ArushiSinghal ?

**Comment by ArushiSinghal** [comment]
@vicky002 web2py is a web-framework just like Django or Ruby on Rails. and we have the separate section for the both so I think for web2py there should be a different section.Also for web2py, there are many learning resources which I will keep on adding as I found.
Also mixing everything in python section will not do justice to both web2py and python.
@vicky002 please let me know your viewpoint.

**Comment by vicky002** [comment]
@ArushiSinghal hmmm I agree and we have Django Resource as a separate section so this make sense.  Merging your PR and looking forward to more contributions from you. 👍

**Comment by vicky002** [comment]
@ArushiSinghal , please add `Web2py` in the main `README.md` file so that people can easily find it. 🙂

**Pull request merged**
