### PR TITLE
Add Android sources

### PR DESCRIPTION
**Pull request by abhilashshakti**
Added a new section for Android. This would be useful to many.
Let's discuss and make new editions.

Thanks

### CODE REVIEW

**Comment by vicky002** [comment]
Hey thanks for contributing to AlgoWiki. That resource is already known by many, I'd suggest you to add few more resources please. 

Let me know your thoughts on this. I can still merge this PR but adding few more resources will make it a good one. :+1:  :heart: :slightly_smiling_face: 

~ Vikesh

**Comment by abhilashshakti** [comment]
Added new sections and resources. Please check.
Let me know if further changes are required.

Thanks

**Comment by vicky002** [comment]
You did great! Thank you so much! :heart: 

Work Harder. Do More.  :+1: 

~ VIkesh

**Comment by abhilashshakti** [comment]
My first pull into the main branch.
Thanks Vikesh!

**Pull request merged**
