### PR TITLE
added few books to competitve programming and Algorithms. Also, added…

### PR DESCRIPTION
**Pull request by Vishwajeet-11**
Screenshot 2022-01-15 at 1 20 39 AM
Screenshot 2022-01-15 at 1 19 29 AM

### CODE REVIEW

**Comment by Vishwajeet-11** [comment]
can someone please tell me why it is showing 'Review required' and 'merging is blocked'. 
Is it normal or i did something wrong, i am complete newbie.

**Review by SARANYA233 — APPROVED** [review]
Approved this pull request

**Review by SARANYA233 — COMMENTED** [review]
can be approved

**Comment by kalyansa23** [comment]
@vicky002 verify and Approve this pull request

**Review by Byte7 — APPROVED** [review]

**Pull request merged**
