### PR TITLE
Added Files

### PR DESCRIPTION
**Pull request by mihirambli**
Added pdf documents for basics of R divided into 3 sessions

### CODE REVIEW

**Review by Byte7 — CHANGES_REQUESTED** [review]
Hi @mihirambli , the books are great but we can not add pdf files to repo as it makes the size bigger and takes more to clone. You can put up these books on drive or dropbox and then add the links to these in resources.md file under Books section. Please make these changes, I'll merge PR then 👍

**Comment by mihirambli** [comment]
Made the changes as asked. Added links to resources.md and removed the files added previously.

**Comment by vicky002** [comment]
@Byte7 have a look at the above changes and merge it if it all looks good.

**Comment by Byte7** [comment]
@mihirambli it looks like your repository is few commits behind. This will lead to merge conflicts for us. Please pull the changes from this repository and make a new branch. Add your links to the topic under new branch and then send in a pull request. This will help resolve the conflicts. 
Aside from that the changes look good, I'll merge them once the conflicts are resolved.
Sorry for bothering you! Love from AlgoWiki ! 👍

**Comment by codingonHP** [comment]
Closing this due to long inactivity and original PR source is no longer available.

**Pull request closed without merging**
