### PR TITLE
Patchup- Fabulous Resources added

### PR DESCRIPTION
**Pull request by shreyateeza**
Adds to #227.
Nice Initiative!

### CODE REVIEW

**Review by Byte7 — CHANGES_REQUESTED** [review]
@shreyateeza These are links to paid stuff. We, at AlgoWiki are only collecting non-paid links, so that it is accessible for everyone. Please look at the Contribution guidelines. You can contribute to any of the topics in AlgoWiki, not just those in issues but only non-paid links.

**Comment by shreyateeza** [comment]
@Byte7 Yeah the guidelines. I saw them. Actually I followed this course of udemy and took glimpses of the bash pocket reference. These resources are amazing and complete in itself. That's why I wrote patchup **fabulous** resources.

Also, I sincerely take the criticism..

**Comment by Byte7** [comment]
@shreyateeza I know there are a lot of paid good courses but unfortunately we cannot include them here. You can try contributing to the Machine Learning topic, you can contribute links to important research papers such as NALU, GAN, etc. or any other topic you love. It's a whole lot of topics here!

**Comment by shreyateeza** [comment]
Will create a new PR when I find free resources.

**Pull request closed without merging**
