### PR TITLE
Updated rust_resources.md and resources.md (interviews)

### PR DESCRIPTION
**Pull request by nikinath**
- Added several resources (including links to official pages) for Rust. Also improved the formatting.
- Added a similar github repo for interviews.

### CODE REVIEW

**Comment by vicky002** [comment]
Hi, Thank you for contributing to AlgoWiki and helping us in collecting and curating all the CS resources at one place! 

Just one point - It would be good if you add a link to `rust` folder in the main [README.md](https://github.com/nikinath/AlgoWiki/blob/gh-pages/README.md) file.

**Comment by vicky002** [comment]
Also `squash` all the commits into one 👍

**Comment by nikinath** [comment]
The link to the Rust folder already exists under the Navigation section (correct me if I am wrong). But I have added Rust in the list of programming languages. 

Let me know if this is fine or you want me to change anything. 

Thank you!

**Comment by vicky002** [comment]
Oh yes! 

Thank you for Contributing to AlgoWiki! :tada: :raised_hands:

**Pull request merged**
