### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by herkura**
Added Git and github tutorial

### CODE REVIEW

**Review by codingonHP — APPROVED** [review]

**Comment by Anjalisharma3463** [comment]
Hey , @codingonHP , i've added a new and really good git resource . I hope it gets merged .#527
Thank you !

**Comment by Anjalisharma3463** [comment]
Hey , @codingonHP , i've added a new and really good git resource . I hope it gets merged .#527
Thank you ! @vicky002

**Comment by Anjalisharma3463** [comment]
Hey , @codingonHP , i've added a new and really good git resource . I hope it gets merged .#527
Thank you ! @vicky002

**Comment by Anjalisharma3463** [comment]
Hey , @codingonHP , i've added a new and really good git resource . I hope it gets merged .#527
Thank you !

**Pull request merged**
