### PR TITLE
Fix typo in Data Science.md

### PR DESCRIPTION
**Pull request by s4chin**

### CODE REVIEW

**Comment by vicky002** [comment]
Seems like there is some conflict. @s4chin

**Comment by s4chin** [comment]
Resolved 👍

**Comment by havanagrawal** [comment]
This has already been fixed 😃

**Comment by vicky002** [comment]
@s4chin @havanagrawal there is still conflicts.

**Comment by havanagrawal** [comment]
@vicky002 What I meant is, the problem this PR is trying to fix was already fixed as part of another PR #164 , so this one can be closed.

**Pull request closed without merging**
