### PR TITLE
Add links to C++ resources

### PR DESCRIPTION
**Pull request by kalabukdima**

### CODE REVIEW

**Review by Byte7 — COMMENTED** [review]
@kalabukdima We, at Algowiki, do not collect paid links to any resource. I'll be removing the book links. The framework link is cool though. Thanks ! Keep contributing to AlgoWiki ! 👍

**Review by Byte7 — APPROVED** [review]

**Comment by kalabukdima** [comment]
Oh, sorry, I missed that. "A tour of C++" book is freely available though. Please consider keeping link to it as it is, in my opinion, a really great book briefly covering most features of C++.

**Comment by Byte7** [comment]
I checked it @kalabukdima . It's a paid book. Here's the [link](http://www.pearsoned.co.uk/bookshop/detail.asp?item=100000000555425). Please correct me if wrong, I'll make the changes. Keep contributing !

**Comment by kalabukdima** [comment]
> I checked it @kalabukdima . It's a paid book. Here's the [link](http://www.pearsoned.co.uk/bookshop/detail.asp?item=100000000555425). Please correct me if wrong, I'll make the changes. Keep contributing !

You're right. The full paperback edition is paid. But there is a draft version provided at [https://isocpp.org/tour](https://isocpp.org/tour) (links: [1](https://isocpp.org/images/uploads/2-Tour-Basics.pdf), [2](https://isocpp.org/images/uploads/3-Tour-Abstr.pdf), [3](https://isocpp.org/files/papers/4-Tour-Algo-draft.pdf), [4](https://isocpp.org/files/papers/5-Tour-Util.pdf)) which is pretty good and doesn't have noticeable disadvantages except for watermarks.
I'll understand if you don't want to have a draft version in this list.

**Comment by Byte7** [comment]
@kalabukdima my bad ! 😅 Send in a PR with the change, I'll merge! 🙌 Keep up the good work.

**Pull request merged**
