### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by AdityaSrivastava185**
Added Frontend Mentor to the list of resources of JavaScript directory #444

### CODE REVIEW

**Review by rajeevkumar504 — APPROVED** [review]
Link works perfectly fine. Thanks for contributing to this repository.
Keep contribute🚀.

**Comment by AdityaSrivastava185** [comment]
Thank you sir , But I am unable to merge the changes because of the warning saying "REVIEW REQUIRED" and saying "At least 1 approving review is required by reviewers with write access"
Please Help and review my changes

**Review by AdityaSrivastava185 — COMMENTED** [review]
Unable to merge the changes please review again and help me to merge because it's saying "REVIEW REQUIRED" and "At least 1 approving review is required by reviewers with write access"

**Review by rajeevkumar504 — APPROVED** [review]
I really appreciate your contribution. The resources you provide are great and I am thankful for your help. Thank you!
Keep Contribute 🚀.

**Review by rajeevkumar504 — APPROVED** [review]
I really appreciate your contribution. The resources you provide are great and I am thankful for your help. Thank you!

**Comment by AdityaSrivastava185** [comment]
Sir I can not merge the pull request as it showing me that "At least 1 approving review is required by reviewers with write access" 
please merge the pull request because it's approved 
Only member with reviewer with write access can merge the pull request

**Review by rajeevkumar504 — CHANGES_REQUESTED** [review]
Do some little bit of changes to it then I will review it again.

**Review by AdityaSrivastava185 — COMMENTED** [review]
review please

**Review by rajeevkumar504 — APPROVED** [review]
Thank you for making changes.

**Review by rajeevkumar504 — APPROVED** [review]

**Comment by AdityaSrivastava185** [comment]
Screenshot 2023-08-07 005036
Saying this , Please help

**Comment by rajeevkumar504** [comment]
Sorry Brother, I try my best but it's okay it happens sometimes. But Keep
Contributing and explore some important resources like these ones:
https://goodfirstissue.dev/
https://os.pradumnasaraf.dev/#/
https://finder.eddiehub.io/
https://www.firsttimersonly.com/

**Comment by AdityaSrivastava185** [comment]
Thank you

**Review by rajeevkumar504 — APPROVED** [review]

**Pull request closed without merging**
